# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'consultaProdutos_.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(725, 462)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabelaConsultaProdutos = QtWidgets.QTableWidget(self.centralwidget)
        self.tabelaConsultaProdutos.setGeometry(QtCore.QRect(25, 131, 611, 301))
        self.tabelaConsultaProdutos.setObjectName("tabelaConsultaProdutos")
        self.tabelaConsultaProdutos.setColumnCount(6)
        self.tabelaConsultaProdutos.setRowCount(13)
        item = QtWidgets.QTableWidgetItem()
        self.tabelaConsultaProdutos.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelaConsultaProdutos.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelaConsultaProdutos.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelaConsultaProdutos.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelaConsultaProdutos.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelaConsultaProdutos.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelaConsultaProdutos.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelaConsultaProdutos.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelaConsultaProdutos.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelaConsultaProdutos.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelaConsultaProdutos.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelaConsultaProdutos.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelaConsultaProdutos.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabelaConsultaProdutos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabelaConsultaProdutos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabelaConsultaProdutos.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabelaConsultaProdutos.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabelaConsultaProdutos.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabelaConsultaProdutos.setHorizontalHeaderItem(5, item)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 30, 151, 17))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(80, 100, 141, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 100, 51, 17))
        self.label_2.setObjectName("label_2")
        self.btnPesquisar = QtWidgets.QPushButton(self.centralwidget)
        self.btnPesquisar.setGeometry(QtCore.QRect(230, 100, 89, 25))
        self.btnPesquisar.setObjectName("btnPesquisar")
        self.btnNovo = QtWidgets.QPushButton(self.centralwidget)
        self.btnNovo.setGeometry(QtCore.QRect(430, 100, 101, 25))
        self.btnNovo.setObjectName("btnNovo")
        self.btnVoltar = QtWidgets.QPushButton(self.centralwidget)
        self.btnVoltar.setGeometry(QtCore.QRect(540, 100, 89, 25))
        self.btnVoltar.setObjectName("btnVoltar")
        self.btnEditar = QtWidgets.QPushButton(self.centralwidget)
        self.btnEditar.setGeometry(QtCore.QRect(330, 100, 89, 25))
        self.btnEditar.setObjectName("btnEditar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 725, 22))
        self.menubar.setObjectName("menubar")
        self.menusair = QtWidgets.QMenu(self.menubar)
        self.menusair.setObjectName("menusair")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionsair = QtWidgets.QAction(MainWindow)
        self.actionsair.setObjectName("actionsair")
        self.menusair.addAction(self.actionsair)
        self.menubar.addAction(self.menusair.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Consulta Produtos"))
        item = self.tabelaConsultaProdutos.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tabelaConsultaProdutos.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tabelaConsultaProdutos.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tabelaConsultaProdutos.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tabelaConsultaProdutos.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tabelaConsultaProdutos.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.tabelaConsultaProdutos.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.tabelaConsultaProdutos.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.tabelaConsultaProdutos.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "9"))
        item = self.tabelaConsultaProdutos.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "10"))
        item = self.tabelaConsultaProdutos.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "11"))
        item = self.tabelaConsultaProdutos.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "12"))
        item = self.tabelaConsultaProdutos.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "13"))
        item = self.tabelaConsultaProdutos.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "idProduto"))
        item = self.tabelaConsultaProdutos.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "nome"))
        item = self.tabelaConsultaProdutos.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "descricao"))
        item = self.tabelaConsultaProdutos.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "qtd_estoque"))
        item = self.tabelaConsultaProdutos.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "qtde_minimo"))
        item = self.tabelaConsultaProdutos.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "valor_produto"))
        self.label.setText(_translate("MainWindow", "Consulta de produtos"))
        self.label_2.setText(_translate("MainWindow", "Nome:"))
        self.btnPesquisar.setText(_translate("MainWindow", "Pesquisar"))
        self.btnNovo.setText(_translate("MainWindow", "Novo Produto"))
        self.btnVoltar.setText(_translate("MainWindow", "Voltar"))
        self.btnEditar.setText(_translate("MainWindow", "Editar"))
        self.menusair.setTitle(_translate("MainWindow", "Consulta"))
        self.actionsair.setText(_translate("MainWindow", "sair"))
