# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interface/consultaProdutos.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(584, 304)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.resultadoConsulta = QtWidgets.QListView(self.centralwidget)
        self.resultadoConsulta.setGeometry(QtCore.QRect(20, 70, 541, 192))
        self.resultadoConsulta.setObjectName("resultadoConsulta")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 50, 71, 17))
        self.label.setObjectName("label")
        self.linePesquisar = QtWidgets.QLineEdit(self.centralwidget)
        self.linePesquisar.setGeometry(QtCore.QRect(120, 10, 221, 25))
        self.linePesquisar.setObjectName("linePesquisar")
        self.btnPesquisar = QtWidgets.QPushButton(self.centralwidget)
        self.btnPesquisar.setGeometry(QtCore.QRect(20, 10, 89, 25))
        self.btnPesquisar.setObjectName("btnPesquisar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 584, 22))
        self.menubar.setObjectName("menubar")
        self.menuConsultar = QtWidgets.QMenu(self.menubar)
        self.menuConsultar.setObjectName("menuConsultar")
        MainWindow.setMenuBar(self.menubar)
        self.actionSair = QtWidgets.QAction(MainWindow)
        self.actionSair.setObjectName("actionSair")
        self.menuConsultar.addAction(self.actionSair)
        self.menubar.addAction(self.menuConsultar.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Consulta Produtos"))
        self.label.setText(_translate("MainWindow", "Resultado"))
        self.btnPesquisar.setText(_translate("MainWindow", "Pesquisar"))
        self.menuConsultar.setTitle(_translate("MainWindow", "Pesquisar"))
        self.actionSair.setText(_translate("MainWindow", "Sair"))
