# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Home.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Home(object):
    def setupUi(self, Home):
        Home.setObjectName("Home")
        Home.resize(600, 600)
        Home.setMinimumSize(QtCore.QSize(600, 600))
        Home.setMaximumSize(QtCore.QSize(600, 600))
        self.centralwidget = QtWidgets.QWidget(Home)
        self.centralwidget.setObjectName("centralwidget")
        self.content = QtWidgets.QFrame(self.centralwidget)
        self.content.setGeometry(QtCore.QRect(0, 10, 600, 600))
        self.content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content.setObjectName("content")
        self.logo = QtWidgets.QLabel(self.content)
        self.logo.setGeometry(QtCore.QRect(150, 80, 300, 61))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.logo.setFont(font)
        self.logo.setObjectName("logo")
        self.label = QtWidgets.QLabel(self.content)
        self.label.setGeometry(QtCore.QRect(40, 230, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.listWidget = QtWidgets.QListWidget(self.content)
        self.listWidget.setGeometry(QtCore.QRect(40, 260, 521, 261))
        self.listWidget.setObjectName("listWidget")
        Home.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Home)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 22))
        self.menubar.setObjectName("menubar")
        self.menuHome = QtWidgets.QMenu(self.menubar)
        self.menuHome.setObjectName("menuHome")
        self.menuEstoque = QtWidgets.QMenu(self.menubar)
        self.menuEstoque.setObjectName("menuEstoque")
        self.menuUsu_rios = QtWidgets.QMenu(self.menubar)
        self.menuUsu_rios.setObjectName("menuUsu_rios")
        self.menuProdutos = QtWidgets.QMenu(self.menubar)
        self.menuProdutos.setObjectName("menuProdutos")
        self.menuMovimenta_o = QtWidgets.QMenu(self.menubar)
        self.menuMovimenta_o.setObjectName("menuMovimenta_o")
        self.menuLogout = QtWidgets.QMenu(self.menubar)
        self.menuLogout.setObjectName("menuLogout")
        Home.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Home)
        self.statusbar.setObjectName("statusbar")
        Home.setStatusBar(self.statusbar)
        self.actionir_para = QtWidgets.QAction(Home)
        self.actionir_para.setObjectName("actionir_para")
        self.actionVer_Estoque = QtWidgets.QAction(Home)
        self.actionVer_Estoque.setObjectName("actionVer_Estoque")
        self.actionConsultar = QtWidgets.QAction(Home)
        self.actionConsultar.setObjectName("actionConsultar")
        self.actionCadastrar_Novo = QtWidgets.QAction(Home)
        self.actionCadastrar_Novo.setObjectName("actionCadastrar_Novo")
        self.actionConsultar_2 = QtWidgets.QAction(Home)
        self.actionConsultar_2.setObjectName("actionConsultar_2")
        self.actionConsultar_3 = QtWidgets.QAction(Home)
        self.actionConsultar_3.setObjectName("actionConsultar_3")
        self.actionSair = QtWidgets.QAction(Home)
        self.actionSair.setObjectName("actionSair")
        self.menuHome.addSeparator()
        self.menuHome.addAction(self.actionir_para)
        self.menuEstoque.addAction(self.actionVer_Estoque)
        self.menuUsu_rios.addAction(self.actionConsultar)
        self.menuUsu_rios.addAction(self.actionCadastrar_Novo)
        self.menuProdutos.addAction(self.actionConsultar_2)
        self.menuMovimenta_o.addAction(self.actionConsultar_3)
        self.menuLogout.addAction(self.actionSair)
        self.menubar.addAction(self.menuHome.menuAction())
        self.menubar.addAction(self.menuEstoque.menuAction())
        self.menubar.addAction(self.menuUsu_rios.menuAction())
        self.menubar.addAction(self.menuProdutos.menuAction())
        self.menubar.addAction(self.menuMovimenta_o.menuAction())
        self.menubar.addAction(self.menuLogout.menuAction())

        self.retranslateUi(Home)
        QtCore.QMetaObject.connectSlotsByName(Home)

    def retranslateUi(self, Home):
        _translate = QtCore.QCoreApplication.translate
        Home.setWindowTitle(_translate("Home", "MainWindow"))
        self.logo.setText(_translate("Home", "Projeto Estoque"))
        self.label.setText(_translate("Home", "Status do estoque:"))
        self.menuHome.setTitle(_translate("Home", "Home"))
        self.menuEstoque.setTitle(_translate("Home", "Estoque"))
        self.menuUsu_rios.setTitle(_translate("Home", "Usuários"))
        self.menuProdutos.setTitle(_translate("Home", "Produtos"))
        self.menuMovimenta_o.setTitle(_translate("Home", "Movimentação"))
        self.menuLogout.setTitle(_translate("Home", "Logout"))
        self.actionir_para.setText(_translate("Home", "Pagina Inicial"))
        self.actionVer_Estoque.setText(_translate("Home", "Consultar"))
        self.actionConsultar.setText(_translate("Home", "Consultar"))
        self.actionCadastrar_Novo.setText(_translate("Home", "Cadastrar Novo"))
        self.actionConsultar_2.setText(_translate("Home", "Consultar"))
        self.actionConsultar_3.setText(_translate("Home", "Consultar"))
        self.actionSair.setText(_translate("Home", "Sair"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Home = QtWidgets.QMainWindow()
    ui = Ui_Home()
    ui.setupUi(Home)
    Home.show()
    sys.exit(app.exec_())

